

# importing the module

from youtube_transcript_api import YouTubeTranscriptApi

transcript_list = YouTubeTranscriptApi.list_transcripts('SW14tOda_kI')

# iterate over all available transcripts
for transcript in transcript_list:
    # the Transcript object provides metadata
    # properties
    '''
    print(
        transcript.video_id,
        transcript.language,
        transcript.language_code,

        # whether it has been manually created or
        # generated by YouTube
        transcript.is_generated,

        # whether this transcript can be translated
        # or not
        transcript.is_translatable,

        # a list of languages the transcript can be
        # translated to
        transcript.translation_languages,
    )
'''
    # fetch the actual transcript data
    t = transcript.fetch()
    print(t)

'''
    # translating the transcript will return another
    # transcript object
    print(transcript.translate('en').fetch())
'''
# you can also directly filter for the language you are
# looking for, using the transcript list
transcript = transcript_list.find_transcript(['en'])

# or just filter for manually created transcripts
transcript = transcript_list.find_manually_created_transcript(['en'])


sent = []
'''


'''

for i in range(0,len(transcript.fetch()),2):
    sent.append(t[i]['text'] )

d = ''
for i in range(len(sent)):
    d+=sent[i]

print(sent)
print(d)

